### ISSUE TITLE
[Crash] Search in REI crashes game, blames kibe

### ISSUE THREAD

**Issue by sarifynna** [lucaargolo/kibe#103]
Hi! While I have your mod loaded I crash when I type in the roughly enough items search box. I hate having your mod disabled because I love it so much! Not enough crashes said the possible mod(s) causing the crash are kibe, architecture API, and or REI.

[crash-2021-09-23_13.39.45-client.txt](https://github.com/lucaargolo/kibe/files/7220081/crash-2021-09-23_13.39.45-client.txt)
[2021-09-23-2.log.gz](https://github.com/lucaargolo/kibe/files/7220083/2021-09-23-2.log.gz)

**Comment by frikinjay** [comment]
Can confirm the crash with a similar log. Looks like something to do with architectury?

**Comment by lucaargolo** [comment]
This is weird, at first it looks like a Roughly Enough Items thing, but then if you look closer you see there's patchouli stuff in there, and there's a mixin in the patchouli code as well so it could be a lot of things. Can you send me your mod list?

**Comment by HellboundGlory** [comment]
Crash Report:
https://pastebin.com/w0VKKsHb

I get the same error happens every time i type in the search bar with kibe active works fine when kibe is deactivated.

ModList:
https://pastebin.com/VAGvpvxS

**Comment by itsdinkd** [comment]
Looks like its Indrev + Kibe, possibly something else. But if you remove Indrev, it works.... there must be another conflicting causing this trifecta conflicting. 

It happens on my modpack AQM2 as well. modlist: https://pastebin.com/syUnxYpJ

**Comment by red2blue** [comment]
@HellboundGlory  Please create a pastebin with your modlist taken from crash report or latest.log this way I can run a difference and see which mods we have

**Comment by itsdinkd** [comment]
Also if oyu look at latest.log when you get this error, you receive a completely different crash report. 


Caused by: java.lang.IllegalArgumentException: Cannot set property class_2758{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in Block{minecraft:air}
	at net.minecraft.state.State.with(State:117) ~[?:?]
	at io.github.lucaargolo.kibe.fluids.miscellaneous.LiquidXpFluid.toBlockState(LiquidXpFluid.kt:17) ~[kibe-1.9.2-BETA+1.17.jar:?]
	at net.minecraft.fluid.FluidState.getBlockState(FluidState:96) ~[?:?]
	at dev.architectury.hooks.fluid.fabric.FluidStackHooksImpl.getNameClient(FluidStackHooksImpl.java:58) ~[architectury-2.5.30-fabric.jar:?]
	at dev.architectury.hooks.fluid.fabric.FluidStackHooksImpl.getName(FluidStackHooksImpl.java:50) ~[architectury-2.5.30-fabric.jar:?]
	at dev.architectury.hooks.fluid.FluidStackHooks.getName(FluidStackHooks.java) ~[architectury-2.5.30-fabric.jar:?]
	at dev.architectury.fluid.FluidStack.getName(FluidStack.java:149) ~[architectury-2.5.30-fabric.jar:?]
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition.asFormattedText(FluidEntryDefinition.java:181) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition.asFormattedText(FluidEntryDefinition.java:81) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.asFormattedText(AbstractEntryStack.java:231) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition$FluidEntryRenderer.getTooltip(FluidEntryDefinition.java:278) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:181) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:81) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:208) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:193) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:177) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:57) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:46) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
[14:31:36] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.'
[14:31:36] [Render thread/INFO]: OpenGL debug message: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.'
[14:31:36] [Render thread/FATAL]: Unreported exception thrown!
java.lang.IllegalArgumentException: Cannot set property class_2758{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in Block{minecraft:air}
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.52) ~[?:?]
	at net.minecraft.state.State.with(State:117) ~[?:?]
	at io.github.lucaargolo.kibe.fluids.miscellaneous.LiquidXpFluid.toBlockState(LiquidXpFluid.kt:17) ~[kibe-1.9.2-BETA+1.17.jar:?]
	at net.minecraft.fluid.FluidState.getBlockState(FluidState:96) ~[?:?]
	at dev.architectury.hooks.fluid.fabric.FluidStackHooksImpl.getNameClient(FluidStackHooksImpl.java:58) ~[architectury-2.5.30-fabric.jar:?]
	at dev.architectury.hooks.fluid.fabric.FluidStackHooksImpl.getName(FluidStackHooksImpl.java:50) ~[architectury-2.5.30-fabric.jar:?]
	at dev.architectury.hooks.fluid.FluidStackHooks.getName(FluidStackHooks.java) ~[architectury-2.5.30-fabric.jar:?]
	at dev.architectury.fluid.FluidStack.getName(FluidStack.java:149) ~[architectury-2.5.30-fabric.jar:?]
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition.asFormattedText(FluidEntryDefinition.java:181) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition.asFormattedText(FluidEntryDefinition.java:81) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.asFormattedText(AbstractEntryStack.java:231) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition$FluidEntryRenderer.getTooltip(FluidEntryDefinition.java:278) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:181) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:81) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:208) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:193) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:177) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:57) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:46) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106) ~[RoughlyEnoughItems-6.0.279-alpha-fabric.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
[14:31:36] [Render thread/FATAL]: Minecraft ran into a problem! Report saved to: D:\minecraftmods\Instances\Another Quality Modpack 2 (1)\crash-reports\crash-2021-10-05_14.31.36-client.txt

**Comment by itsdinkd** [comment]
Indrev + Kibe were working before I updated mods after 10/1 

Here are the updated mods, maybe something you can recognize in this list? (minus kibe and indrev, readded them)

![image](https://user-images.githubusercontent.com/35115304/136107553-7770c455-19d9-41ea-8dfa-cfcc8ba447ab.png)

**Comment by Lionexx** [comment]
Adding my crash report to this post, same issue as above

https://paste.ee/p/r0vg0

**Comment by lucaargolo** [comment]
This issue should be fixed in the 1.9.3-BETA update. If it somehow persists, I'll reopen this issue and reinvestigate its cause.
