### ISSUE TITLE
Liquid XP Fluid crash

### ISSUE THREAD

**Issue by DillonHHH** [lucaargolo/kibe#108]
`Time: 10/8/21, 4:57 PM
Description: Getting tooltips

java.lang.IllegalArgumentException: Cannot set property class_2758{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in Block{minecraft:air}
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61)
	at net.minecraft.state.State.with(State:117)
	at io.github.lucaargolo.kibe.fluids.miscellaneous.LiquidXpFluid.toBlockState(LiquidXpFluid.kt:17)
	at net.minecraft.fluid.FluidState.getBlockState(FluidState:96)
	at dev.architectury.hooks.fluid.fabric.FluidStackHooksImpl.getNameClient(FluidStackHooksImpl.java:58)
	at dev.architectury.hooks.fluid.fabric.FluidStackHooksImpl.getName(FluidStackHooksImpl.java:50)
	at dev.architectury.hooks.fluid.FluidStackHooks.getName(FluidStackHooks.java)
	at dev.architectury.fluid.FluidStack.getName(FluidStack.java:149)
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition.asFormattedText(FluidEntryDefinition.java:181)
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition.asFormattedText(FluidEntryDefinition.java:81)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.asFormattedText(AbstractEntryStack.java:231)
	at me.shedaniel.rei.plugin.client.entry.FluidEntryDefinition$FluidEntryRenderer.getTooltip(FluidEntryDefinition.java:278)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:181)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:81)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:208)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:193)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:177)
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:57)
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:46)
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138)
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2688.method_11657(class_2688.java:117)
	at io.github.lucaargolo.kibe.fluids.miscellaneous.LiquidXpFluid.method_15790(LiquidXpFluid.kt:17)
	at net.minecraft.class_3610.method_15759(class_3610.java:96)
	at dev.architectury.hooks.fluid.fabric.FluidStackHooksImpl.getNameClient(FluidStackHooksImpl.java:58)
	at dev.architectury.hooks.fluid.fabric.FluidStackHooksImpl.getName(FluidStackHooksImpl.java:50)
	at dev.architectury.hooks.fluid.FluidStackHooks.getName(FluidStackHooks.java)
	at dev.architectury.fluid.FluidStack.getName(FluidStack.java:149)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$haj000$fillPatchouliContext(class_128.java:1521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:35)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.getTooltip(AbstractEntryStack.java:195)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.tryGetEntryStackTooltip(TooltipArgumentType.java:81)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:74)
	at me.shedaniel.rei.impl.client.search.argument.type.TooltipArgumentType.matches(TooltipArgumentType.java:44)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:208)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:193)
	at me.shedaniel.rei.impl.client.search.argument.Argument.matches(Argument.java:177)
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:57)
	at me.shedaniel.rei.impl.client.search.SearchProviderImpl$SearchFilterImpl.test(SearchProviderImpl.java:46)
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.matches(AsyncSearchManager.java:138)
	at me.shedaniel.rei.impl.client.search.AsyncSearchManager.lambda$get$3(AsyncSearchManager.java:106)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
`

Can consistently reproduce by opening REI and typing "g".  May be considered a bug with REI (sorry if so) but upon removing the mod everything seems to be working fine.

**Comment by DillonHHH** [comment]
nevermind this, just realized it's a duplicate and that it's a bug with Kibe and searching anything in REI
