### ISSUE TITLE
crash with immersive portals

### ISSUE THREAD

**Issue by scaryshadow** [lucaargolo/kibe#12]
Minecraft 1.16.1 crashes when Kibe 1.1.12 and Immersive Portals are both installed. Previous versions of Kibe worked fine with Immersive Portals. I tried getting the crash report, but they're not being created so I'm not sure how else to help. Here's a log file, I dunno if it'll help.

[23:07:34] [main/INFO]: Loading for game Minecraft 1.16.1
[23:07:34] [main/INFO]: [FabricLoader] Loading 55 mods: fabric-renderer-api-v1@0.2.13+eae12eb802, fabric-keybindings-v0@0.2.0+3fa9f7c502, fabricloader@0.9.0+build.204, org_jetbrains_kotlinx_kotlinx-coroutines-core@1.3.7, fabric-containers-v0@0.1.8+045df74f02, fabric-object-builder-api-v1@1.5.6+a2d21ddd02, fabric-dimensions-v1@1.0.0+a71b305302, kibe@1.1.12-BETA, fabric-game-rule-api-v1@1.0.0+fe81e12502, fabric-api-base@0.1.3+12a8474c02, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d02, fabric-textures-v0@1.0.4+eae12eb802, fabric-rendering-fluids-v1@0.1.8+b7084faa02, org_jetbrains_kotlin_kotlin-stdlib@1.3.72, playerabilitylib@1.2.0, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8902, fabric-lifecycle-events-v1@1.1.0+013e49d202, immersive_portals@0.17, fabric-renderer-registries-v1@2.0.1+5a0f9a6002, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.3.72, fabric-loot-tables-v1@1.0.0+386eb69e02, fabric@0.16.0+build.384-1.16.1, fabric-particles-v1@0.2.1+0a6f2a7002, fabric-networking-v0@0.1.10+e00ecb5f02, minecraft@1.16.1, fabric-screen-handler-api-v1@1.1.0+97324d1102, fabric-networking-blockentity-v0@0.2.5+b50ffc7b02, modmenu@1.11.8+build.13, cloth-basic-math@0.5.1, fabric-command-api-v1@1.0.8+5ce5339802, fabric-tool-attribute-api-v1@1.2.0+55e0cc5f02, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.3.72, fabric-renderer-indigo@0.3.4+34d6c87102, fabric-biomes-v1@0.2.7+059ea86602, fabric-item-api-v1@1.0.0+16acbe5b02, fabric-events-interaction-v0@0.3.3+7066030f02, fabric-crash-report-info-v1@0.1.2+b7f9825d02, fabric-language-kotlin@1.3.72+build.1, fabric-rendering-v0@1.1.0+5341049002, fabric-rendering-v1@1.1.2+346247d702, fabric-key-binding-api-v1@1.0.1+f404f3be02, cloth-config2@4.5.0-unstable, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.3.7, fabric-resource-loader-v0@0.2.6+f41e209802, org_jetbrains_kotlin_kotlin-reflect@1.3.72, fabric-content-registries-v0@0.1.9+059ea86602, fabric-tag-extensions-v0@0.2.7+a4c57d8e02, fabric-registry-sync-v0@0.3.8+7dba2d6c02, fabric-commands-v0@0.2.0+52d3083602, fabric-mining-levels-v0@0.1.2+b764ce9902, fabric-events-lifecycle-v0@0.2.0+16acbe5b02, fabric-item-groups-v0@0.2.0+438f963602, fabric-models-v0@0.1.0+dfdb52d602, fabric-object-builders-v0@0.6.1+a2d21ddd02, org_jetbrains_annotations@17.0.0
[23:07:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/joshu/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[23:07:36] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[23:07:37] [main/WARN]: @Redirect conflict. Skipping immersive_portals.mixins.json:MixinServerWorld->@Redirect::redirectGetForcedChunks(Lnet/minecraft/class_3218;)Lit/unimi/dsi/fastutil/longs/LongSet; with priority 1000, already redirected by kibe.mixins.json:ServerWorldMixin->@Redirect::redirectGetForcedChunksOnTick(Lnet/minecraft/class_3218;)Lit/unimi/dsi/fastutil/longs/LongSet; with priority 1000

**Comment by nephatrine** [comment]
Also getting a crash trying to start with immersive portals in 1.16.2 now that it's out there.

```
[11:04:04] [main/WARN]: @Redirect conflict. Skipping kibe.mixins.json:ServerWorldMixin->@Redirect::redirectGetForcedChunksOnTick(Lnet/minecraft/class_3218;)Lit/unimi/dsi/fastutil/longs/LongSet; with priority 1000, already redirected by imm_ptl.mixins.json:common.MixinServerWorld->@Redirect::redirectGetForcedChunks(Lnet/minecraft/class_3218;)Lit/unimi/dsi/fastutil/longs/LongSet; with priority 1000
org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetForcedChunksOnTick(Lnet/minecraft/class_3218;)Lit/unimi/dsi/fastutil/longs/LongSet; in kibe.mixins.json:ServerWorldMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap kibe-1.16.2-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_2246.<clinit>(class_2246.java:99)
	at net.minecraft.class_3523.<clinit>(class_3523.java:13)
	at net.minecraft.class_5471.<clinit>(class_5471.java:11)
	at net.minecraft.class_5458.method_30573(class_5458.java:44)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at java.util.LinkedHashMap.forEach(Unknown Source)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:237)
	at net.minecraft.class_2966.method_12851(class_2966.java:42)
	at net.minecraft.client.main.Main.main(Main.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_2246.<clinit>(class_2246.java:99)
	at net.minecraft.class_3523.<clinit>(class_3523.java:13)
	at net.minecraft.class_5471.<clinit>(class_5471.java:11)
	at net.minecraft.class_5458.method_30573(class_5458.java:44)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at java.util.LinkedHashMap.forEach(Unknown Source)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:237)
	at net.minecraft.class_2966.method_12851(class_2966.java:42)
	at net.minecraft.client.main.Main.main(Main.java:137)
	... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetForcedChunksOnTick(Lnet/minecraft/class_3218;)Lit/unimi/dsi/fastutil/longs/LongSet; in kibe.mixins.json:ServerWorldMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap kibe-1.16.2-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 23 more
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128M; support was removed in 8.0
```

**Comment by CygnusiaX1** [comment]
Same issue. Copy/pasting the section of the log with the crash:
`[11:13:44] [main/WARN]: @Redirect conflict. Skipping kibe.mixins.json:ServerWorldMixin->@Redirect::redirectGetForcedChunksOnTick(Lnet/minecraft/class_3218;)Lit/unimi/dsi/fastutil/longs/LongSet; with priority 1000, already redirected by imm_ptl.mixins.json:common.MixinServerWorld->@Redirect::redirectGetForcedChunks(Lnet/minecraft/class_3218;)Lit/unimi/dsi/fastutil/longs/LongSet; with priority 1000
org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetForcedChunksOnTick(Lnet/minecraft/class_3218;)Lit/unimi/dsi/fastutil/longs/LongSet; in kibe.mixins.json:ServerWorldMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap kibe-1.16.3-refmap.json`

**Comment by lucaargolo** [comment]
Can't reproduce in the latest release of Immersive Portals... Guess they fixed it!
