### ISSUE TITLE
Kibe's crashing Server when playing in single player

### ISSUE THREAD

**Issue by Laifsyn** [lucaargolo/kibe#150]
I got this crash when in **_singleplayer_** Like why does it say server? xd
[latest.log](https://github.com/lucaargolo/kibe/files/8548840/latest.-.Copy.log)
[Relevant Session](https://pastebin.com/aTrmtUPr)
`[19:45:06] [Server thread/INFO]: [STDOUT]: Saving player: false
[19:45:07] [Netty Server IO #1/ERROR]: Encountered exception while handling in channel with name "kibe:request_dirty_tank_states"
java.lang.IndexOutOfBoundsException: readerIndex(34) + length(1) exceeds writerIndex(34): UnpooledSlicedByteBuf(ridx: 34, widx: 34, cap: 34/34, unwrapped: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 34, cap: 256))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
	at net.minecraft.class_2540.readByte(class_2540.java:1013) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10816(class_2540.java:344) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10800(class_2540.java:495) ~[client-intermediary.jar:?]
	at io.github.lucaargolo.kibe.KibeModKt.initPackets$lambda-5(KibeMod.kt:157) ~[kibe-1.9.7-BETA+1.18.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:89) ~[fabric-networking-api-v1-1.0.21+d882b91560-8caffa82fdcf8532.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:38) ~[fabric-networking-api-v1-1.0.21+d882b91560-8caffa82fdcf8532.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) [fabric-networking-api-v1-1.0.21+d882b91560-8caffa82fdcf8532.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:84) [fabric-networking-api-v1-1.0.21+d882b91560-8caffa82fdcf8532.jar:?]
	at net.minecraft.class_3244.handler$cjp000$handleCustomPayloadReceivedAsync(class_3244.java:1714) [client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12075(class_3244.java) [client-intermediary.jar:?]
	at net.minecraft.class_2817.method_12199(class_2817.java:38) [client-intermediary.jar:?]
	at net.minecraft.class_2817.method_11054(class_2817.java:7) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:172) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:157) [client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:55) [client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.68.Final.jar:4.1.68.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[19:45:07] [Server thread/INFO]: Laifsyn lost connection: Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(34) + length(1) exceeds writerIndex(34): UnpooledSlicedByteBuf(ridx: 34, widx: 34, cap: 34/34, unwrapped: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 34, cap: 256))
[19:45:07] [Server thread/INFO]: Laifsyn left the game`

**Comment by Laifsyn** [comment]
For more context. I was just afk in the same place
