### ISSUE TITLE
Rendering the tanks at the bottom of the kibe creative tab causes game crash

### ISSUE THREAD

**Issue by Justsnoopy30** [lucaargolo/kibe#154]
```[17:33:02] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering item
	at net.minecraft.class_757.method_3192(class_757.java:886) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1122) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [universe-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [universe-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [universe-loader-0.14.4.jar:?]
Caused by: java.lang.NullPointerException: fluidSprite must not be null
	at io.github.lucaargolo.kibe.items.tank.TankBlockItemBakedModel.emitItemQuads(TankBlockItemBakedModel.kt:76) ~[kibe-1.9.7-BETA+1.18.jar:?]
	at link.infra.indium.renderer.render.ItemRenderContext.renderModel(ItemRenderContext.java:110) ~[indium-1.0.3+mc1.18.2.jar:?]
	at net.minecraft.class_918.handler$cll000$hook_renderItem(link/infra/indium/mixin/renderer/MixinItemRenderer.java [indium.mixins.json]:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_23179(class_918.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_4021(class_918.java:306) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_4026(class_918.java:349) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_36543(class_918.java:339) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_27951(class_918.java:335) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_2385(class_465.java:264) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:122) ~[client-intermediary.jar:?]
	at net.minecraft.class_485.method_25394(class_485.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_481.method_25394(class_481.java:679) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:877) ~[client-intermediary.jar:?]
	... 10 more
```

**Comment by Justsnoopy30** [comment]
Figured out how to reproduce this consistently, go to the kibe section of the creative menu and scroll to the bottom. You will crash with this every time.

**Comment by Justsnoopy30** [comment]
Crash report: [crash-2022-05-08_18.18.46-client.txt](https://github.com/lucaargolo/kibe/files/8647985/crash-2022-05-08_18.18.46-client.txt)

**Comment by lucaargolo** [comment]
This is being caused by an improperly textured fluid. "create:potion" to be more specific. Could you try placing the fluid in the world? It'll probably crash as well, in any case, I think this should be reported to the create devs.

**Comment by Justsnoopy30** [comment]
I did not realize I got a response, sorry. create:potion doesn't show up in /give, /setblock, or REI at all so I'm not sure how I could place it.

**Comment by Justsnoopy30** [comment]
This was actually an issue between colormatic and create, updating colormatic fixed it, sorry for the inconvenience.
