### ISSUE TITLE
An Unexpected Issue Occurred

### ISSUE THREAD

**Issue by FrozenFruit108** [lucaargolo/kibe#37]
Hi! I've been having issues with this mod not working. The game crashes and says "An unexpected issue occurred and the game crashed. We're sorry for the inconvenience." Are there any things I could do to stop this from happening? I know that immersive portals doesn't work with this mod, but I don't have that installed right now. Are there any other mods that conflict with this one, or any tips in general?

**Comment by Technici4n** [comment]
Can you post the log, please? It should be in a folder in your minecraft instance.

**Comment by FrozenFruit108** [comment]
Here's the Log:

[09:50:35] [main/INFO]: Loading for game Minecraft 1.16.2
[09:50:36] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.1.3+12a8474cfa, also found 0.1.3+12a8474c95, 0.1.3+12a8474c4e, 0.1.3+12a8474ca7
 - Conflicting versions found for fabric-networking-v0: used 0.1.10+e00ecb5f4e, also found 0.1.10+e00ecb5fa7, 0.1.10+e00ecb5f95
 - Conflicting versions found for fabric-resource-loader-v0: used 0.3.1+facf3bbf4e, also found 0.3.1+facf3bbf95
 - Conflicting versions found for fabric-textures-v0: used 1.0.4+eae12eb84e, also found 1.0.4+eae12eb895
 - Mod durabilityviewer recommends mod {modupdater @ [>=1.1.7]}, which is missing!
[09:50:36] [main/WARN]: Mod `lightoverlay` (5.5.0) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[09:50:36] [main/WARN]: Mod `harvest` (1.2.12) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[09:50:36] [main/INFO]: [FabricLoader] Loading 134 mods: fallflyinglib@1.1.0, soitburns@1.0.0, fabric-keybindings-v0@0.2.0+3fa9f7c54e, roughlyenoughitems-api@5.4.2, deadtotems@0.1.1+1.16.3, carvepump@1.0.3, cloth-common-events-v1@1.4.8, fabricloader@0.9.3+build.207, trinkets@2.6.4, cloth-durability-bar-api-v1@1.4.8, kibe@1.4.5-BETA, megane@1.2.0+1.16, fabric-game-rule-api-v1@1.0.1+91555cd14e, modify-drops-api@0.2.1, bettercaves@1.16.2-1.0.1, fabric-api-base@0.1.3+12a8474cfa, elytra_bounce@0.1.0+1.16.1, xaeroworldmap@1.11.0, ccspecialorgans@1.0.2, roughlyenoughresources@2.1.1, chestcavity@1.2.5, blackstonetools@1.2.0+1.16.1, decorative@2.0.1, org_jetbrains_kotlin_kotlin-stdlib@1.4.0, waila@1.9.22, playerabilitylib@1.2.1, fabric-blockrenderlayer-v1@1.1.4+c6a8ea894e, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.0, libblockattributes_items@0.8.0-pre.18, fabric@0.20.1+build.401-1.16, fabric-networking-v0@0.1.10+e00ecb5f4e, fabric-screen-handler-api-v1@1.1.0+872498414e, modmenu@1.14.6+build.31, cloth-utils-v1@1.4.8, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.0, fabric-tool-attribute-api-v1@1.2.2+ccce563e4e, roughlyenoughitems-runtime@5.4.2, cloth-client-events-v0@1.4.8, blockus@1.6.4, fabric-events-interaction-v0@0.4.1+f8ac1db295, fabric-crash-report-info-v1@0.1.2+b7f9825d4e, disablecustomworldsadvice@1.1, mostructures@1.0.0-pre3+mc.1.16.2, backpackmod@1.16.2-1.2.1, fabric-language-kotlin@1.4.0+build.1, origins@1.16.3-0.3.8, nbtcrafting@2.0.0+mc1.16.2-pre1, betterweather@1.0.0, fabric-key-binding-api-v1@1.0.1+730711c64e, cloth-config2@4.8.1, soulsandstone@0.0.2, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.3.9, fabric-resource-loader-v0@0.3.1+facf3bbf4e, megane-runtime@1.2.0+1.16, org_jetbrains_kotlin_kotlin-reflect@1.4.0, cardinal-components-entity@2.6.0, libblockattributes_fluids@0.8.2, fabric-registry-sync-v0@0.5.1+f8ac1db295, fabric-commands-v0@0.2.0+52d308364e, cardinal-components-base@2.6.0, lightoverlay@5.5.0, fabric-mining-levels-v0@0.1.2+b764ce994e, the_bumblezone@1.16.3-2.2.6, woodsplus@0.0.2, earthtojavamobs@1.2.0+1.16.2, fabric-item-groups-v0@0.2.0+438f96364e, fabric-models-v0@0.1.0+dfdb52d64e, extraalchemy@1.3.0, org_jetbrains_annotations@20.0.0, fabric-renderer-api-v1@0.3.0+8bcfced84e, parchment@1.0.2+1.15.2, gbfabrictools@1.2.3+1.16.2, megane-api@1.2.0+1.16, libcd@2.5.0+1.16.1, cavebiomes@0.3.0, easierenchanting@1.3.0, fabric-structure-api-v1@1.0.1+fb0d9b0e4e, falling_tree@2.5.1, fabric-containers-v0@0.1.8+045df74f4e, fabric-object-builder-api-v1@1.7.0+432ea1884e, vanincoex@0.1.2, banner_capes@0.2.1, libblockattributes@0.8.0-pre.18, plantinajar@1.7.1+1.16.2, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d4e, mm@2.1, cloth-dynamic-registry-api-v1@1.4.8, campanion@1.2.0+build.39, fabric-textures-v0@1.0.4+eae12eb84e, elytra-recipe@1.0.0, fabric-rendering-fluids-v1@0.1.11+fb0d9b0e4e, reach-entity-attributes@1.0.1, bedspreads@1.2.0-1.16.3, cloth-scissors-api-v1@1.4.8, fabric-lifecycle-events-v1@1.2.0+74cc3b204e, fabric-renderer-registries-v1@2.2.0+f8ac1db295, fabric-loot-tables-v1@1.0.1+432ea1884e, cloth-armor-api-v1@1.4.8, fabric-particles-v1@0.2.2+fb0d9b0e4e, libblockattributes_core@0.8.2, more_gems@1.1.2, minecraft@1.16.2, fabric-networking-blockentity-v0@0.2.5+b50ffc7b4e, roughlyenoughitems-default-plugin@5.4.2, cloth-basic-math@0.5.1, jankson@3.0.1+j1.2.0, fabric-command-api-v1@1.0.8+5ce533984e, origins-classes@1.16.2-1.0.1, fabric-renderer-indigo@0.4.0+8bcfced84e, roughlyenoughitems@5.4.2, fabric-item-api-v1@1.1.0+29679fd64e, libgui@3.0.0-beta.1+1.16.2-rc2, drunkfletchintable@0.1.1, xaerominimap@20.24.0, fabric-rendering-v0@1.1.0+534104904e, fabric-rendering-v1@1.3.1+f8ac1db295, missingnetherblocks@2.0.0, autoconfig1u@3.2.2, winged@1.16.2-1.4.0, megane-impl@1.2.0+1.16, harvest@1.2.12, fabric-content-registries-v0@0.1.9+059ea8664e, fabric-tag-extensions-v0@1.0.3+ac8e8c594e, optifabric@1.5.0, cloth-api@1.4.8, durabilityviewer@1.16.2-fabric0.17.2-1.8.7, carrier@1.3.0, cloth-datagen-api-v1@1.4.8, fabric-events-lifecycle-v0@0.2.0+16acbe5b4e, melonslabs@1.1.0, inventorytabs@0.2.2-1.16.2, minegate-moreblocks@1.0.1, mighty_mangoes@1.0.3, fabric-object-builders-v0@0.7.0+432ea1884e
[09:50:41] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:/C:/Users/Keoni/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.1+build.21/sponge-mixin-0.8.1+build.21.jar Service=Knot/Fabric Env=CLIENT
[09:50:41] [main/WARN]: Reference map 'blackstone-tools-refmap.json' for blackstonetools.mixins.json could not be read. If this is a development environment you can ignore this message
[09:50:41] [main/WARN]: Reference map 'woods-plus-refmap.json' for woodsplus.mixins.json could not be read. If this is a development environment you can ignore this message
[09:50:41] [main/WARN]: Reference map 'soul-sandstone-refmap.json' for soulsandstone.mixins.json could not be read. If this is a development environment you can ignore this message
[09:50:42] [main/WARN]: Error loading class: appeng/integration/modules/waila/TileWailaDataProvider (java.lang.ClassNotFoundException: appeng/integration/modules/waila/TileWailaDataProvider)
[09:50:42] [main/WARN]: @Mixin target appeng.integration.modules.waila.TileWailaDataProvider was not found megane-impl.mixins.json:appeng.MixinTileWailaDataProvider
[09:50:42] [main/WARN]: Error loading class: draylar/fabricfurnaces/entity/BaseFurnaceEntity (java.lang.ClassNotFoundException: draylar/fabricfurnaces/entity/BaseFurnaceEntity)
[09:50:42] [main/WARN]: @Mixin target draylar.fabricfurnaces.entity.BaseFurnaceEntity was not found megane-impl.mixins.json:fabricfurnaces.AccessorBaseFurnaceEntity
[09:50:42] [main/WARN]: Error loading class: aztech/modern_industrialization/blocks/creativetank/CreativeTankBlockEntity (java.lang.ClassNotFoundException: aztech/modern_industrialization/blocks/creativetank/CreativeTankBlockEntity)
[09:50:42] [main/WARN]: @Mixin target aztech.modern_industrialization.blocks.creativetank.CreativeTankBlockEntity was not found megane-impl.mixins.json:modern_industrialization.AccessorCreativeTankBlockEntity
[09:50:42] [main/WARN]: Error loading class: aztech/modern_industrialization/machines/impl/MachineBlockEntity (java.lang.ClassNotFoundException: aztech/modern_industrialization/machines/impl/MachineBlockEntity)
[09:50:42] [main/WARN]: @Mixin target aztech.modern_industrialization.machines.impl.MachineBlockEntity was not found megane-impl.mixins.json:modern_industrialization.AccessorMachineBlockEntity
[09:50:42] [main/WARN]: Error loading class: aztech/modern_industrialization/blocks/tank/TankBlockEntity (java.lang.ClassNotFoundException: aztech/modern_industrialization/blocks/tank/TankBlockEntity)
[09:50:42] [main/WARN]: @Mixin target aztech.modern_industrialization.blocks.tank.TankBlockEntity was not found megane-impl.mixins.json:modern_industrialization.AccessorTankBlockEntity
[09:50:42] [main/WARN]: @Mixin target me/shedaniel/rei/server/RecipeFinder is public in nbtcrafting.compat.mixins.json:MixinREIRecipeFinder and should be specified in value
[09:50:44] [main/FATAL]: Mixin apply failed fallflyinglib.mixins.json:LivingEntityMixin -> net.minecraft.class_1309: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Specified index 1 for @ModifyArg is invalid for args (Lnet/minecraft/class_1309;IZ), expected Z on net/minecraft/class_1309::patchInitAi [INJECT Applicator Phase -> fallflyinglib.mixins.json:LivingEntityMixin -> Apply Injections ->  -> Inject -> fallflyinglib.mixins.json:LivingEntityMixin->@ModifyArg::patchInitAi(Z)Z]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Specified index 1 for @ModifyArg is invalid for args (Lnet/minecraft/class_1309;IZ), expected Z on net/minecraft/class_1309::patchInitAi [INJECT Applicator Phase -> fallflyinglib.mixins.json:LivingEntityMixin -> Apply Injections ->  -> Inject -> fallflyinglib.mixins.json:LivingEntityMixin->@ModifyArg::patchInitAi(Z)Z]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.findArgIndex(ModifyArgInjector.java:157) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.injectAtInvoke(ModifyArgInjector.java:112) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.injection.invoke.InvokeInjector.inject(InvokeInjector.java:82) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.injection.invoke.ModifyArgInjector.inject(ModifyArgInjector.java:102) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [sponge-mixin-0.8.1+build.21.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-loader-0.9.3+build.207.jar:0.8.1+build.21+unknown-b21.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148) [fabric-loader-0.9.3+build.207.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) [?:1.8.0_51]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) [?:1.8.0_51]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161) [fabric-loader-0.9.3+build.207.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.ClassLoader.defineClass1(Native Method) [?:1.8.0_51]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) [?:1.8.0_51]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) [?:1.8.0_51]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161) [fabric-loader-0.9.3+build.207.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_51]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:261) [Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_559(class_128.java:101) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.class_128.<init>(class_128.java:54) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:413) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:135) [intermediary-fabric-loader-0.9.3+build.207-1.16.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.3+build.207.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.3+build.207.jar:?]

I'm very inexperienced with modding, so any help would be really appreciated

**Comment by lucaargolo** [comment]
Are you sure Kibe is the one causing the game to crash? Have you tried removing it to see if the game loads? Btw, why aren't you on 1.16.3? Also, I've noticed you're using optifine, this is most likely not an issue, but if you could remove it to test if the game loads without it it would be nice.

**Comment by adriantodt** [comment]
Elytra Bounce and FallFlyingLib are at fault. See https://github.com/adriantodt/FallFlyingLib/issues/2

**Comment by FrozenFruit108** [comment]
I got rid of Elytra Bounce and it worked. Thank you!
