### ISSUE TITLE
java.lang.NoClassDefFoundError: net.minecraft.class_746

### ISSUE THREAD

**Issue by TheEssem** [lucaargolo/kibe#4]
When attempting to use the slimesling/slime boots on a Fabric server, the server crashes after letting go of the right mouse button. Here's the log when it occurs:
```
[08:58:27] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net.minecraft.class_746
	at Not Enough Crashes deobfuscated stack trace.(1.16.1+build.17) ~[?:?]
	at io.github.lucaargolo.kibe.utils.SlimeBounceHandler.<init>(SlimeBounceHandler.java:18) ~[kibe-1.16.1-1.1.3-BETA.jar:?]
	at io.github.lucaargolo.kibe.utils.SlimeBounceHandler$Companion.addBounceHandler(SlimeBounceHandler.java:36) ~[kibe-1.16.1-1.1.3-BETA.jar:?]
	at io.github.lucaargolo.kibe.items.miscellaneous.SlimeSling.onStoppedUsing(SlimeSling.java:62) ~[kibe-1.16.1-1.1.3-BETA.jar:?]
	at net.minecraft.item.ItemStack.onStoppedUsing(ItemStack:485) ~[?:?]
	at net.minecraft.entity.LivingEntity.stopUsingItem(LivingEntity:2947) ~[?:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerAction(ServerPlayNetworkHandler:939) ~[?:?]
	at net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket.apply(PlayerActionC2SPacket:40) ~[?:?]
	at net.minecraft.network.packet.c2s.play.PlayerActionC2SPacket.apply(PlayerActionC2SPacket:10) ~[?:?]
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21) ~[?:?]
	at net.minecraft.class_2600$$Lambda$5461/0000000000000000.run(Unknown Source) ~[?:?]
	at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:763) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:154) ~[intermediary-server.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer:745) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:739) ~[intermediary-server.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer:724) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer:676) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:256) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$4504/0000000000000000.run(Unknown Source) [intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:788) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:1081) ~[?:?]
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:56) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:1081) ~[?:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:1081) ~[?:?]
	... 24 more
```
This line seems to be the culprit: https://github.com/lucaargolo/kibe/blob/master/src/main/kotlin/io/github/lucaargolo/kibe/utils/SlimeBounceHandler.kt#L18

**Comment by lucaargolo** [comment]
Hey, thanks for the report. It should be fixed in 1.1.3
