### ISSUE TITLE
Vacuum Hopper Crashes Game

### ISSUE THREAD

**Issue by queenielawrens** [lucaargolo/kibe#78]
Vacuum Hopper when viewed makes the game freeze. Does not resolve and the window has to be closed. 

Mod Version: Kibe 1.7-BETA

Note: I had other mods loaded at the time and was moving around a debug world when the game first crashed. However, when tested in a normal (non-debug) world, placing a vacuum hopper causes the same effect with the same messages in the log.

Log: 
```
[19:02:00] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking block entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:96) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5575.method_31794()" because "â˜ƒ" is null
	at net.minecraft.class_5572.method_31762(class_5572.java:40) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at net.minecraft.class_5573.method_31774(class_5573.java:127) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at net.minecraft.class_5573.method_31777(class_5573.java:64) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at net.minecraft.class_5573.method_31773(class_5573.java:127) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at net.minecraft.class_5578.method_31805(class_5578.java:47) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at net.minecraft.class_1937.method_18023(class_1937.java:631) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at io.github.lucaargolo.kibe.blocks.vacuum.VacuumHopperEntity$Companion.tick(VacuumHopperEntity.java:242) ~[kibe-1.17-pre1-1.7-BETA.jar:?]
	at io.github.lucaargolo.kibe.blocks.vacuum.VacuumHopper.getTicker$lambda-0(VacuumHopper.java:37) ~[kibe-1.17-pre1-1.7-BETA.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:886) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:941) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:474) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:423) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893) ~[intermediary-minecraft-1.17-pre5-client.jar:?]
	... 5 more
[19:02:00] [Server thread/ERROR]: This crash report has been saved to: C:\Users\aweso\Documents\Setup\MultiMC\instances\QoF 0.15\.minecraft\crash-reports\crash-2021-06-03_19.02.00-server.txt
[19:02:00] [Server thread/INFO]: Stopping server
[19:02:00] [Server thread/INFO]: Saving players
[19:02:00] [Server thread/INFO]: QueenieLawrens lost connection: Disconnected
[19:02:00] [Server thread/INFO]: QueenieLawrens left the game
[19:02:00] [Server thread/INFO]: Stopping singleplayer server as player logged out
[19:02:00] [Server thread/INFO]: Saving worlds
[19:02:00] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[19:02:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World (3)): All chunks are saved
[19:02:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[19:02:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[19:02:02] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[19:02:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[19:02:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World (3)): All chunks are saved
[19:02:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[19:02:02] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
Process was killed by user.
```

**Comment by lucaargolo** [comment]
Oh sorry, i forgot to close this issue but this bug was probably fixed in 189e8a6f7904d9c252d792a2fc798142afd5d4a2
